// <auto-generated/>
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


internal class BC_2DPoint : BC_ControllableData {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal BC_2DPoint(global::System.IntPtr cPtr, bool cMemoryOwn) : base(BIMcollab_2DPointPINVOKE.BC_2DPoint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BC_2DPoint obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BC_2DPoint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BIMcollab_2DPointPINVOKE.delete_BC_2DPoint(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public BC_2DPoint(double x, double y) : this(BIMcollab_2DPointPINVOKE.new_BC_2DPoint(x, y), true) {
  }

  public double GetX() {
    double ret = BIMcollab_2DPointPINVOKE.BC_2DPoint_GetX(swigCPtr);
    return ret;
  }

  public double GetY() {
    double ret = BIMcollab_2DPointPINVOKE.BC_2DPoint_GetY(swigCPtr);
    return ret;
  }

}
