// <auto-generated/>
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


internal class BC_Approver : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BC_Approver(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BC_Approver obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BC_Approver() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BIMcollab_IssuePINVOKE.delete_BC_Approver(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public BC_User m_pUser {
    set {
      BIMcollab_IssuePINVOKE.BC_Approver_m_pUser_set(swigCPtr, BC_User.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BIMcollab_IssuePINVOKE.BC_Approver_m_pUser_get(swigCPtr);
      BC_User ret = (cPtr == global::System.IntPtr.Zero) ? null : new BC_User(cPtr, false);
      return ret;
    } 
  }

  public bool m_hasApproved {
    set {
      BIMcollab_IssuePINVOKE.BC_Approver_m_hasApproved_set(swigCPtr, value);
    } 
    get {
      bool ret = BIMcollab_IssuePINVOKE.BC_Approver_m_hasApproved_get(swigCPtr);
      return ret;
    } 
  }

  public BC_Approver() : this(BIMcollab_IssuePINVOKE.new_BC_Approver(), true) {
  }

}
