// <auto-generated/>
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


internal enum BC_BcfVersion {
  bcfVersion_no_bcf = 0,
  bcfVersion_1_0,
  bcfVersion_1_1,
  bcfVersion_2_0,
  bcfVersion_2_1
}
