// <auto-generated/>
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


internal class BC_DocumentReference : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BC_DocumentReference(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BC_DocumentReference obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BC_DocumentReference() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BIMcollab_HelperPINVOKE.delete_BC_DocumentReference(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string GetElementReferenceDocument() {
    string ret = BIMcollab_HelperPINVOKE.BC_DocumentReference_GetElementReferenceDocument(swigCPtr);
    return ret;
  }

  public void SetElementReferenceDocument(string value) {
    BIMcollab_HelperPINVOKE.BC_DocumentReference_SetElementReferenceDocument(swigCPtr, value);
    if (BIMcollab_HelperPINVOKE.SWIGPendingException.Pending) throw BIMcollab_HelperPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetElementDescription() {
    string ret = BIMcollab_HelperPINVOKE.BC_DocumentReference_GetElementDescription(swigCPtr);
    return ret;
  }

  public void SetElementDescription(string value) {
    BIMcollab_HelperPINVOKE.BC_DocumentReference_SetElementDescription(swigCPtr, value);
    if (BIMcollab_HelperPINVOKE.SWIGPendingException.Pending) throw BIMcollab_HelperPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetAttributeGuid() {
    string ret = BIMcollab_HelperPINVOKE.BC_DocumentReference_GetAttributeGuid(swigCPtr);
    return ret;
  }

  public void SetAttributeGuid(string value) {
    BIMcollab_HelperPINVOKE.BC_DocumentReference_SetAttributeGuid(swigCPtr, value);
    if (BIMcollab_HelperPINVOKE.SWIGPendingException.Pending) throw BIMcollab_HelperPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetAttributeIsExternal() {
    bool ret = BIMcollab_HelperPINVOKE.BC_DocumentReference_GetAttributeIsExternal(swigCPtr);
    return ret;
  }

  public void SetAttributeIsExternal(bool value) {
    BIMcollab_HelperPINVOKE.BC_DocumentReference_SetAttributeIsExternal(swigCPtr, value);
  }

  public BC_DocumentReference() : this(BIMcollab_HelperPINVOKE.new_BC_DocumentReference(), true) {
  }

}
