// <auto-generated/>
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


internal class BC_Exception : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BC_Exception(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BC_Exception obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BC_Exception() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BIMcollab_ExceptionPINVOKE.delete_BC_Exception(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public BC_Exception() : this(BIMcollab_ExceptionPINVOKE.new_BC_Exception__SWIG_0(), true) {
  }

  public BC_Exception(uint index, uint size) : this(BIMcollab_ExceptionPINVOKE.new_BC_Exception__SWIG_1(index, size), true) {
  }

  public BC_Exception(int errorCode, string message) : this(BIMcollab_ExceptionPINVOKE.new_BC_Exception__SWIG_2(errorCode, message), true) {
    if (BIMcollab_ExceptionPINVOKE.SWIGPendingException.Pending) throw BIMcollab_ExceptionPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string what() {
    string ret = BIMcollab_ExceptionPINVOKE.BC_Exception_what(swigCPtr);
    return ret;
  }

  public virtual int GetErrorCode() {
    int ret = BIMcollab_ExceptionPINVOKE.BC_Exception_GetErrorCode(swigCPtr);
    return ret;
  }

}
