// <auto-generated/>
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


internal enum BC_ResultCode {
  resultCodeOk = 0,
  resultCodeErrorInterfaceVersion = 1,
  resultCodeErrorConnection = 2,
  resultCodeErrorAuthentication = 3,
  resultCodeErrorInternal = 4,
  resultCodeErrorIndexOutOfRange = 5,
  resultCodeErrorNoData = 6,
  resultCodeErrorNotFound = 7,
  resultCodeErrorCannotLoadFile = 8,
  resultCodeErrorCannotSaveFile = 9,
  resultCodeErrorUserNotActive = 10,
  resultCodeErrorUserNotAssignable = 11,
  resultCodeErrorUserNotSpecified = 12,
  resultCodeErrorNotActiveProject = 13,
  resultCodeErrorInvalidGuid = 14,
  resultCodeErrorNotOffline = 15,
  resultCodeErrorEmptyValue = 17,
  resultCodeErrorInvalidState = 18,
  resultCodeErrorNullPointer = 19,
  resultCodeErrorNotAllowed = 20,
  resultCodeErrorExistingGuid = 21,
  resultCodeErrorInvalidTimestamp = 22,
  resultCodeErrorDbAtFault = 23,
  resultCodeErrorPosixTimeNotSet = 24,
  resultCodeErrorUndefined = 25,
  resultCodeErrorProcessingData = 26,
  resultCodeErrorSoap = 27,
  resultCodeErrorIssueModiffied = 28,
  resultCodeErrorInvalidToken = 29,
  resultCodeErrorEditRightRevoked = 30,
  resultCodeErrorAssignRightRevoked = 31,
  resultCodeErrorChangeVisibilityNotAllowed = 32,
  resultCodeErrorInactivePropertyValue = 33,
  resultCodeErrorValueMadeUnavailableIssueType = 34,
  resultCodeErrorValueMadeUnavailableIssueLabel = 35,
  resultCodeErrorValueMadeUnavailableIssueVisibility = 36,
  resultCodeErrorValueMadeUnavailableIssueArea = 37,
  resultCodeErrorValueMadeUnavailableIssueMilestone = 38,
  resultCodeErrorProjectNotActive = 39,
  resultCodeErrorClosingRightRevoked = 40,
  resultCodeErrorExceedingMaxNrOfComponents = 41,
  resultCodeErrorExceedingMaxNrOfLines = 42,
  resultCodeErrorExceedingMaxNrOfClippingplanes = 43,
  resultCodeErrorInvalidCsv = 44,
  resultCodeErrorMemoryAllocationFailed = 46,
  resultCodeErrorInvalidUser = 47,
  resultCodeErrorInvalidValue = 48,
  resultCodeErrorInvalidIfcguid = 49,
  resultCodeErrorInvalidArgument = 50,
  resultCodeErrorNotApprover = 51,
  resultCodeErrorUserInCollection = 52
}
