// <auto-generated/>
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


internal class BC_User : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BC_User(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BC_User obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BC_User() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BIMcollab_UserPINVOKE.delete_BC_User(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string GetName() {
    string ret = BIMcollab_UserPINVOKE.BC_User_GetName(swigCPtr);
    return ret;
  }

  public string GetFirstName() {
    string ret = BIMcollab_UserPINVOKE.BC_User_GetFirstName(swigCPtr);
    return ret;
  }

  public string GetLastName() {
    string ret = BIMcollab_UserPINVOKE.BC_User_GetLastName(swigCPtr);
    return ret;
  }

  public string GetEmail() {
    string ret = BIMcollab_UserPINVOKE.BC_User_GetEmail(swigCPtr);
    return ret;
  }

  public string GetGuid() {
    string ret = BIMcollab_UserPINVOKE.BC_User_GetGuid(swigCPtr);
    return ret;
  }

  public bool CanBecomeOwner() {
    bool ret = BIMcollab_UserPINVOKE.BC_User_CanBecomeOwner(swigCPtr);
    return ret;
  }

  public bool CanBecomeApprover() {
    bool ret = BIMcollab_UserPINVOKE.BC_User_CanBecomeApprover(swigCPtr);
    return ret;
  }

  public bool CanBeNotified() {
    bool ret = BIMcollab_UserPINVOKE.BC_User_CanBeNotified(swigCPtr);
    return ret;
  }

  public bool IsDeleted() {
    bool ret = BIMcollab_UserPINVOKE.BC_User_IsDeleted(swigCPtr);
    return ret;
  }

  public bool IsProjectLeader() {
    bool ret = BIMcollab_UserPINVOKE.BC_User_IsProjectLeader(swigCPtr);
    return ret;
  }

  public string GetInitials() {
    string ret = BIMcollab_UserPINVOKE.BC_User_GetInitials(swigCPtr);
    return ret;
  }

  public BC_User() : this(BIMcollab_UserPINVOKE.new_BC_User(), true) {
  }

}
