// <auto-generated/>
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


[System.CodeDom.Compiler.GeneratedCode("SWIG", "3.0.2")]
class BIMcollab_ProjectPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="SWIGRegisterExceptionCallbacks_BIMcollab_Project", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    public static extern void SWIGRegisterExceptionCallbacks_BIMcollab_Project(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_BIMcollab_Project", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    public static extern void SWIGRegisterExceptionCallbacksArgument_BIMcollab_Project(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_BIMcollab_Project(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_BIMcollab_Project(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(BIMcollab_ProjectPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(BIMcollab_ProjectPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="SWIGRegisterStringCallback_BIMcollab_Project", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    public static extern void SWIGRegisterStringCallback_BIMcollab_Project(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_BIMcollab_Project(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static BIMcollab_ProjectPINVOKE() {
  }


  protected class SWIGWStringHelper {

    [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]
	public delegate string SWIGWStringDelegate(global::System.IntPtr message);
    static SWIGWStringDelegate wstringDelegate = new SWIGWStringDelegate(CreateWString);

    [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="SWIGRegisterWStringCallback_BIMcollab_Project", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    public static extern void SWIGRegisterWStringCallback_BIMcollab_Project(SWIGWStringDelegate wstringDelegate);

    static string CreateWString([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]global::System.IntPtr cString) {
        //string result = global::System.Runtime.InteropServices.Marshal.PtrToStringUni(cString);
        //return result;
		return global::System.Runtime.InteropServices.Marshal.PtrToStringUni(cString);
    }

    static SWIGWStringHelper() {
      SWIGRegisterWStringCallback_BIMcollab_Project(wstringDelegate);
    }
  }

  static protected SWIGWStringHelper swigWStringHelper = new SWIGWStringHelper();


  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Progress_action_set", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Progress_action_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Progress_action_get", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Progress_action_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Progress_index_set", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Progress_index_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Progress_index_get", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Progress_index_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Progress_nrTotal_set", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Progress_nrTotal_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Progress_nrTotal_get", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Progress_nrTotal_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Progress_nrFailed_set", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Progress_nrFailed_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Progress_nrFailed_get", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Progress_nrFailed_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_new_BC_Progress", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr new_BC_Progress();

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_delete_BC_Progress", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void delete_BC_Progress(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfIssues", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfIssues(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssueByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Project_GetIssueByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfUsers", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfUsers(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetUserByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Project_GetUserByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetTitle", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetTitle(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetDescription", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetDescription(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetId", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetId(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetStartDate", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetStartDate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetEndDate", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetEndDate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_Reload", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Project_Reload(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_Refresh", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Project_Refresh(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_Publish", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_Publish(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_CreateIssue", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Project_CreateIssue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_CanRemoveIssueByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_CanRemoveIssueByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_RemoveIssueByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Project_RemoveIssueByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_IsOperationAllowed", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_IsOperationAllowed(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetProgress", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Project_GetProgress(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfAreas", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfAreas(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetAreaLabelByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetAreaLabelByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetAreaActiveByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_GetAreaActiveByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfMilestones", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfMilestones(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetMilestoneLabelByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetMilestoneLabelByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetMilestoneActiveByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_GetMilestoneActiveByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_SetActiveUser", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Project_SetActiveUser(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]string jarg2, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]string jarg3, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]string jarg4, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]string jarg5, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]string jarg6);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_HasActiveError", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_HasActiveError(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetActiveError", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Project_GetActiveError(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfMessages", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfMessages(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetMessageByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Project_GetMessageByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfIssueStatuses", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfIssueStatuses(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssueStatusLabelByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetIssueStatusLabelByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssueStatusActiveByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_GetIssueStatusActiveByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetDefaultIssueStatusIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetDefaultIssueStatusIndex(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfIssuePriorities", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfIssuePriorities(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssuePriorityLabelByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetIssuePriorityLabelByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssuePriorityActiveByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_GetIssuePriorityActiveByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetDefaultIssuePriorityIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetDefaultIssuePriorityIndex(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfIssueLabels", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfIssueLabels(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssueLabelLabelByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetIssueLabelLabelByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssueLabelActiveByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_GetIssueLabelActiveByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfIssueTypes", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfIssueTypes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssueTypeLabelByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetIssueTypeLabelByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssueTypeActiveByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_GetIssueTypeActiveByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetDefaultIssueTypeIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetDefaultIssueTypeIndex(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfIssueVisibilities", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfIssueVisibilities(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssueVisibilityLabelByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetIssueVisibilityLabelByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetIssueVisibilityActiveByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Project_GetIssueVisibilityActiveByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetDefaultIssueVisibilityIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetDefaultIssueVisibilityIndex(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetNumberOfProjectionTypes", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetNumberOfProjectionTypes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetProjectionTypeLabelByIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Project_GetProjectionTypeLabelByIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_GetDefaultProjectionTypeIndex", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Project_GetDefaultProjectionTypeIndex(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_new_BC_Project", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr new_BC_Project();

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_delete_BC_Project", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void delete_BC_Project(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Project_SWIGUpcast", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Project_SWIGUpcast(global::System.IntPtr jarg1);
}
