// <auto-generated/>
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


[System.CodeDom.Compiler.GeneratedCode("SWIG", "3.0.2")]
class BIMcollab_DimensionPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="SWIGRegisterExceptionCallbacks_BIMcollab_Dimension", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    public static extern void SWIGRegisterExceptionCallbacks_BIMcollab_Dimension(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_BIMcollab_Dimension", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    public static extern void SWIGRegisterExceptionCallbacksArgument_BIMcollab_Dimension(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_BIMcollab_Dimension(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_BIMcollab_Dimension(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(BIMcollab_DimensionPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(BIMcollab_DimensionPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="SWIGRegisterStringCallback_BIMcollab_Dimension", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    public static extern void SWIGRegisterStringCallback_BIMcollab_Dimension(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_BIMcollab_Dimension(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static BIMcollab_DimensionPINVOKE() {
  }


  protected class SWIGWStringHelper {

    [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]
	public delegate string SWIGWStringDelegate(global::System.IntPtr message);
    static SWIGWStringDelegate wstringDelegate = new SWIGWStringDelegate(CreateWString);

    [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="SWIGRegisterWStringCallback_BIMcollab_Dimension", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    public static extern void SWIGRegisterWStringCallback_BIMcollab_Dimension(SWIGWStringDelegate wstringDelegate);

    static string CreateWString([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]global::System.IntPtr cString) {
        //string result = global::System.Runtime.InteropServices.Marshal.PtrToStringUni(cString);
        //return result;
		return global::System.Runtime.InteropServices.Marshal.PtrToStringUni(cString);
    }

    static SWIGWStringHelper() {
      SWIGRegisterWStringCallback_BIMcollab_Dimension(wstringDelegate);
    }
  }

  static protected SWIGWStringHelper swigWStringHelper = new SWIGWStringHelper();


  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_new_BC_Dimension", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr new_BC_Dimension();

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetFirstPoint", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Dimension_GetFirstPoint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetFirstNormal", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Dimension_GetFirstNormal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetFirstVector", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Dimension_GetFirstVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetFirstType", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Dimension_GetFirstType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetSecondPoint", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Dimension_GetSecondPoint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetSecondNormal", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Dimension_GetSecondNormal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetSecondVector", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Dimension_GetSecondVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetSecondType", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Dimension_GetSecondType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetIsPointToPoint", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern bool BC_Dimension_GetIsPointToPoint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetUpVector", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Dimension_GetUpVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetDirToCameraVector", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Dimension_GetDirToCameraVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetColor", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Dimension_GetColor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetLineWidth", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern double BC_Dimension_GetLineWidth(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetTextHeight", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern double BC_Dimension_GetTextHeight(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetFirstPointSymbol", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Dimension_GetFirstPointSymbol(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetSecondPointSymbol", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern uint BC_Dimension_GetSecondPointSymbol(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetEndPointSymbolHeight", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern double BC_Dimension_GetEndPointSymbolHeight(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_SetFirstPoint", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Dimension_SetFirstPoint(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_SetSecondPoint", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Dimension_SetSecondPoint(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_SetAdditionalParameters", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Dimension_SetAdditionalParameters(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]string jarg5, double jarg6, double jarg7, uint jarg8, uint jarg9, double jarg10);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_GetExtendedData", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern string BC_Dimension_GetExtendedData(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_SetExtendedData", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void BC_Dimension_SetExtendedData(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_delete_BC_Dimension", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern void delete_BC_Dimension(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("BIMcollab_cs", EntryPoint="CSharp_BC_Dimension_SWIGUpcast", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
  public static extern global::System.IntPtr BC_Dimension_SWIGUpcast(global::System.IntPtr jarg1);
}
